name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Publish .NET Core Project
      run: dotnet publish ClientSideSudoku/ClientSideSudoku.csproj -c Release -o release --nologo
    - name: Change base-tag in index.html from / to BlazorGitHubPagesDemo
      run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorSudoku\/" \/>/g' release/wwwroot/index.html
    - name: Commit wwwroot to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.6.0
      with:
        jekyll: false
        build_dir: release/wwwroot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

